name: Deploy to Heroku with Docker

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"  # This will run the workflow every hour

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and Push Docker image to Heroku
      run: |
        echo "$HEROKU_API_KEY" | docker login --username=_ --password-stdin registry.heroku.com
        docker build -t registry.heroku.com/mp-dashboard/web .
        docker push registry.heroku.com/mp-dashboard/web
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    - name: Release Docker image on Heroku
      run: |
        heroku container:release web -a mp-dashboard
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
