name: Deploy to Heroku

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"  # This runs the workflow every hour

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Streamlit app and get_data.py
      run: |
        nohup streamlit run app.py &
        python get_data.py

    - name: Deploy to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        git remote add heroku https://git.heroku.com/mp-dashboard.git
        git push heroku main
